// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdKhY53GJikHzD2dOt6-IhKbRXx5NWOCI',
    appId: '1:494622699243:web:f671a2b99410b503d358ae',
    messagingSenderId: '494622699243',
    projectId: 'portalcelular-c1601',
    authDomain: 'portalcelular-c1601.firebaseapp.com',
    storageBucket: 'portalcelular-c1601.appspot.com',
    measurementId: 'G-WEYY8FP1YL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5BqpzpAuSa015TBH4A_K8N5aSSxoIvyI',
    appId: '1:494622699243:android:b9f4e079785462f9d358ae',
    messagingSenderId: '494622699243',
    projectId: 'portalcelular-c1601',
    storageBucket: 'portalcelular-c1601.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBdKhY53GJikHzD2dOt6-IhKbRXx5NWOCI',
    appId: '1:494622699243:web:0e3dc4feb11291f2d358ae',
    messagingSenderId: '494622699243',
    projectId: 'portalcelular-c1601',
    authDomain: 'portalcelular-c1601.firebaseapp.com',
    storageBucket: 'portalcelular-c1601.appspot.com',
    measurementId: 'G-XHQ8NMTL76',
  );

}